#!/bin/bash
# echo function specified in argument with the SSF info line
#
# e.g. file `example_function` in directory within $FUNCPATH:
#
#	# External comment
#	example_function () {
#		# Internal comment to retain
#		echo "something"
#	}
#
# is printed as
#
#	# SSF: /path/to/example_function, latest
#	example_function () {
#		# Internal comment to retain
#		echo "something"
#	}

#SSF: ~/.functions/file_in_path, latest
file_in_path () {
	# Checks whether the filename is in the specified `*PATH`
	envpath=$1
	if [ -z $envpath ] ; then
		echo "Function: in_path: $envpath is empty."
		exit 1
	fi

	for d in $(echo $envpath | sed 's/:/\n/g')
	do
		func_path="$d/$2"
		if [ -f "$func_path" ] ; then
			found=true
			echo "$func_path"
			return 0
		fi
	done

	echo "Function: in_path: $2 not found"
	return 1 
}

function_path=$(file_in_path $FUNCPATH $1)

if [ $? = 1 ] ; then
	echo "SSF Script: print_function: $1 doesn't exist."
	exit 1
fi

echo "#SSF: $function_path, latest" | sed "s:$HOME:~:"
cat "$function_path" | sed '/^#/d'
